/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as EquipmentRouteImport } from './routes/equipment'
import { Route as DesignersRouteImport } from './routes/designers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookScannerRouteImport } from './routes/book-scanner'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShadeIndexRouteImport } from './routes/shade/index'
import { Route as ClinicsIndexRouteImport } from './routes/clinics/index'
import { Route as TrackingBookingIdRouteImport } from './routes/tracking/$bookingId'
import { Route as EmployeeLoginRouteImport } from './routes/employee/login'
import { Route as EmployeeDashboardRouteImport } from './routes/employee/dashboard'
import { Route as ClinicsIdRouteImport } from './routes/clinics/$id'
import { Route as AdminScannersRouteImport } from './routes/admin/scanners'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminEmployeesRouteImport } from './routes/admin/employees'
import { Route as AdminClinicsRouteImport } from './routes/admin/clinics'
import { Route as AdminBookingsRouteImport } from './routes/admin/bookings'
import { Route as AdminProductionOrderIdRouteImport } from './routes/admin/production/$orderId'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentRoute = EquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignersRoute = DesignersRouteImport.update({
  id: '/designers',
  path: '/designers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookScannerRoute = BookScannerRouteImport.update({
  id: '/book-scanner',
  path: '/book-scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShadeIndexRoute = ShadeIndexRouteImport.update({
  id: '/shade/',
  path: '/shade/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicsIndexRoute = ClinicsIndexRouteImport.update({
  id: '/clinics/',
  path: '/clinics/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingBookingIdRoute = TrackingBookingIdRouteImport.update({
  id: '/tracking/$bookingId',
  path: '/tracking/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeLoginRoute = EmployeeLoginRouteImport.update({
  id: '/employee/login',
  path: '/employee/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeDashboardRoute = EmployeeDashboardRouteImport.update({
  id: '/employee/dashboard',
  path: '/employee/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicsIdRoute = ClinicsIdRouteImport.update({
  id: '/clinics/$id',
  path: '/clinics/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminScannersRoute = AdminScannersRouteImport.update({
  id: '/admin/scanners',
  path: '/admin/scanners',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmployeesRoute = AdminEmployeesRouteImport.update({
  id: '/admin/employees',
  path: '/admin/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClinicsRoute = AdminClinicsRouteImport.update({
  id: '/admin/clinics',
  path: '/admin/clinics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/admin/bookings',
  path: '/admin/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductionOrderIdRoute = AdminProductionOrderIdRouteImport.update({
  id: '/admin/production/$orderId',
  path: '/admin/production/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book-scanner': typeof BookScannerRoute
  '/contact': typeof ContactRoute
  '/designers': typeof DesignersRoute
  '/equipment': typeof EquipmentRoute
  '/portfolio': typeof PortfolioRoute
  '/services': typeof ServicesRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/clinics': typeof AdminClinicsRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/scanners': typeof AdminScannersRoute
  '/clinics/$id': typeof ClinicsIdRoute
  '/employee/dashboard': typeof EmployeeDashboardRoute
  '/employee/login': typeof EmployeeLoginRoute
  '/tracking/$bookingId': typeof TrackingBookingIdRoute
  '/clinics/': typeof ClinicsIndexRoute
  '/shade/': typeof ShadeIndexRoute
  '/admin/production/$orderId': typeof AdminProductionOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book-scanner': typeof BookScannerRoute
  '/contact': typeof ContactRoute
  '/designers': typeof DesignersRoute
  '/equipment': typeof EquipmentRoute
  '/portfolio': typeof PortfolioRoute
  '/services': typeof ServicesRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/clinics': typeof AdminClinicsRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/scanners': typeof AdminScannersRoute
  '/clinics/$id': typeof ClinicsIdRoute
  '/employee/dashboard': typeof EmployeeDashboardRoute
  '/employee/login': typeof EmployeeLoginRoute
  '/tracking/$bookingId': typeof TrackingBookingIdRoute
  '/clinics': typeof ClinicsIndexRoute
  '/shade': typeof ShadeIndexRoute
  '/admin/production/$orderId': typeof AdminProductionOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book-scanner': typeof BookScannerRoute
  '/contact': typeof ContactRoute
  '/designers': typeof DesignersRoute
  '/equipment': typeof EquipmentRoute
  '/portfolio': typeof PortfolioRoute
  '/services': typeof ServicesRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/clinics': typeof AdminClinicsRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/scanners': typeof AdminScannersRoute
  '/clinics/$id': typeof ClinicsIdRoute
  '/employee/dashboard': typeof EmployeeDashboardRoute
  '/employee/login': typeof EmployeeLoginRoute
  '/tracking/$bookingId': typeof TrackingBookingIdRoute
  '/clinics/': typeof ClinicsIndexRoute
  '/shade/': typeof ShadeIndexRoute
  '/admin/production/$orderId': typeof AdminProductionOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/book-scanner'
    | '/contact'
    | '/designers'
    | '/equipment'
    | '/portfolio'
    | '/services'
    | '/admin/bookings'
    | '/admin/clinics'
    | '/admin/employees'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/scanners'
    | '/clinics/$id'
    | '/employee/dashboard'
    | '/employee/login'
    | '/tracking/$bookingId'
    | '/clinics/'
    | '/shade/'
    | '/admin/production/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book-scanner'
    | '/contact'
    | '/designers'
    | '/equipment'
    | '/portfolio'
    | '/services'
    | '/admin/bookings'
    | '/admin/clinics'
    | '/admin/employees'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/scanners'
    | '/clinics/$id'
    | '/employee/dashboard'
    | '/employee/login'
    | '/tracking/$bookingId'
    | '/clinics'
    | '/shade'
    | '/admin/production/$orderId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/book-scanner'
    | '/contact'
    | '/designers'
    | '/equipment'
    | '/portfolio'
    | '/services'
    | '/admin/bookings'
    | '/admin/clinics'
    | '/admin/employees'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/scanners'
    | '/clinics/$id'
    | '/employee/dashboard'
    | '/employee/login'
    | '/tracking/$bookingId'
    | '/clinics/'
    | '/shade/'
    | '/admin/production/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookScannerRoute: typeof BookScannerRoute
  ContactRoute: typeof ContactRoute
  DesignersRoute: typeof DesignersRoute
  EquipmentRoute: typeof EquipmentRoute
  PortfolioRoute: typeof PortfolioRoute
  ServicesRoute: typeof ServicesRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminClinicsRoute: typeof AdminClinicsRoute
  AdminEmployeesRoute: typeof AdminEmployeesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminScannersRoute: typeof AdminScannersRoute
  ClinicsIdRoute: typeof ClinicsIdRoute
  EmployeeDashboardRoute: typeof EmployeeDashboardRoute
  EmployeeLoginRoute: typeof EmployeeLoginRoute
  TrackingBookingIdRoute: typeof TrackingBookingIdRoute
  ClinicsIndexRoute: typeof ClinicsIndexRoute
  ShadeIndexRoute: typeof ShadeIndexRoute
  AdminProductionOrderIdRoute: typeof AdminProductionOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment': {
      id: '/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof EquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designers': {
      id: '/designers'
      path: '/designers'
      fullPath: '/designers'
      preLoaderRoute: typeof DesignersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-scanner': {
      id: '/book-scanner'
      path: '/book-scanner'
      fullPath: '/book-scanner'
      preLoaderRoute: typeof BookScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shade/': {
      id: '/shade/'
      path: '/shade'
      fullPath: '/shade/'
      preLoaderRoute: typeof ShadeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinics/': {
      id: '/clinics/'
      path: '/clinics'
      fullPath: '/clinics/'
      preLoaderRoute: typeof ClinicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking/$bookingId': {
      id: '/tracking/$bookingId'
      path: '/tracking/$bookingId'
      fullPath: '/tracking/$bookingId'
      preLoaderRoute: typeof TrackingBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/login': {
      id: '/employee/login'
      path: '/employee/login'
      fullPath: '/employee/login'
      preLoaderRoute: typeof EmployeeLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/dashboard': {
      id: '/employee/dashboard'
      path: '/employee/dashboard'
      fullPath: '/employee/dashboard'
      preLoaderRoute: typeof EmployeeDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinics/$id': {
      id: '/clinics/$id'
      path: '/clinics/$id'
      fullPath: '/clinics/$id'
      preLoaderRoute: typeof ClinicsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/scanners': {
      id: '/admin/scanners'
      path: '/admin/scanners'
      fullPath: '/admin/scanners'
      preLoaderRoute: typeof AdminScannersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/employees': {
      id: '/admin/employees'
      path: '/admin/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/clinics': {
      id: '/admin/clinics'
      path: '/admin/clinics'
      fullPath: '/admin/clinics'
      preLoaderRoute: typeof AdminClinicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/admin/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/production/$orderId': {
      id: '/admin/production/$orderId'
      path: '/admin/production/$orderId'
      fullPath: '/admin/production/$orderId'
      preLoaderRoute: typeof AdminProductionOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookScannerRoute: BookScannerRoute,
  ContactRoute: ContactRoute,
  DesignersRoute: DesignersRoute,
  EquipmentRoute: EquipmentRoute,
  PortfolioRoute: PortfolioRoute,
  ServicesRoute: ServicesRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminClinicsRoute: AdminClinicsRoute,
  AdminEmployeesRoute: AdminEmployeesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminScannersRoute: AdminScannersRoute,
  ClinicsIdRoute: ClinicsIdRoute,
  EmployeeDashboardRoute: EmployeeDashboardRoute,
  EmployeeLoginRoute: EmployeeLoginRoute,
  TrackingBookingIdRoute: TrackingBookingIdRoute,
  ClinicsIndexRoute: ClinicsIndexRoute,
  ShadeIndexRoute: ShadeIndexRoute,
  AdminProductionOrderIdRoute: AdminProductionOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
